### ISSUE TITLE
Separate Demand Flexibility Data Input

### ISSUE THREAD

**Issue by dongqi-wu** [Breakthrough-Energy/REISE.jl#139]
# :rocket:

- [x] Is your feature request essential for your project?

### Describe the workflow you want to enable
I wish to split the input file for demand flexibility into two files that assign different allowance for shifting the demand upward or downward. This will enable a more flexible behaviour of flexible loads by allowing them to have different extend of flexibility in increasing or curtailing.

### Describe your proposed implementation
The script read.jl should take two csv files: 'demand_flexibility_up.csv' and 'demand_flexibility_dn.csv' instead of a single file 'demand_flexibility.csv'
The class "demand_flexibility" should have two dataframes to hold the data in the input csvs
The upper bound of the decision variables in the opt model 'load_shift_up' and 'load_shift_dn' should be different according to the two input files.

**Comment by lanesmith** [comment]
I think this functionality sounds good and the proposed implementation seems straightforward. There are some other things that would also need to be implemented:
- We would need to update `loop.jl` as well so that the upper bounds on `load_shift_up` and `load_shift_dn` are updated for intervals `i > 2`.
- Within both `model.jl` and `loop.jl`, we would need to call two instances of `_make_bus_demand_flexibility_amount` (right now we only have one) for `bus_flex_amt_up` and `bus_flex_amt_dn`.

Based on Tuesday's discussion, part of the interest in splitting up the demand flexibility parameter (other than for just providing more user flexibility) seemed to be the possibility of having demand that could only be curtailed (i.e., "sheddable demand"). If we want this to truly be explored, we should revisit issue #125, which discusses including a representation of sheddable demand. With the constraints that are established for the current implementation (i.e., "shiftable demand"), the functionality of sheddable demand would not be able to be realized.

**Comment by BainanXia** [comment]
> I think this functionality sounds good and the proposed implementation seems straightforward. There are some other things that would also need to be implemented:
> 
> * We would need to update `loop.jl` as well so that the upper bounds on `load_shift_up` and `load_shift_dn` are updated for intervals `i > 2`.
> * Within both `model.jl` and `loop.jl`, we would need to call two instances of `_make_bus_demand_flexibility_amount` (right now we only have one) for `bus_flex_amt_up` and `bus_flex_amt_dn`.
> 
> Based on Tuesday's discussion, part of the interest in splitting up the demand flexibility parameter (other than for just providing more user flexibility) seemed to be the possibility of having demand that could only be curtailed (i.e., "sheddable demand"). If we want this to truly be explored, we should revisit issue #125, which discusses including a representation of sheddable demand. With the constraints that are established for the current implementation (i.e., "shiftable demand"), the functionality of sheddable demand would not be able to be realized.

Agree. It is tricky to handle load balance during a given time window in the mean time dealing with sheddable demand.
