### ISSUE TITLE
Add an User Option that Allows Users to Specify the Form of  Demand Flexibility Input Data

### ISSUE THREAD

**Issue by dongqi-wu** [Breakthrough-Energy/REISE.jl#141]
# :rocket:

- [x] Is your feature request essential for your project?

### Describe the workflow you want to enable
I wish the user can choose to provide the demand flexibility input data in several different formats and tell the program to interpret through an additional user-specified parameter in `demand_flexibility_parameters.csv`. Currently, the input csv file `demand_flexibility.csv` has the resolution of per-load-zone, which means the program assigns a single number to all loads in every load zone. Issue #140 proposed an improvement to the input data granularity. 

The current implementation add two demand flexibility constraints for each load bus in the case if data is provided. However, in demand response simulations one may be only interested to consider a small subset of load buses in the case that represents aggregated urban or industrial loads. With the current implementation it is impossible to alter the flexibility of individual buses without changing all other load buses in the same load zone. Additionally, if an user just want to study the impact of demand flexibility on a subset of load buses, adding the constraints for the buses that are not assigned to be flexible also introduce unnecessary computation complexity.

### Describe your proposed implementation
* The input file `demand_flexibility_parameters.csv` should have one additional parameter that allows the user to choose from two (more if needed) modes: load-zone level or bus level. For load-zone level input, the user specifies a number for each load zone and the number of columns of `demand_flexibility_parameters.csv` should be exactly equal to the number of load-zones. For bus-level input, the user can specify the flexibility of any number of buses in the system, the number of columns in `demand_flexibility.csv` should be within the range [0, load_bus_num].
* The class `demand_flexibility` should have an additional field corresponding to the new parameter.
* In the data pre-processing in `model.jl`, there function `_make_bus_demand_flexibility_amount()` should check for the new parameter and compute the current demand flexibility matrix. 
* The dimension of decision variables `load_shift_up` and `load_shift_dn` should be equal to the number of load buses that have a non-zero flexibility, instead of all load buses. The parts that place constraints on the two variables should also be changed accordingly.

### Describe alternatives you've considered, if relevant
This proposal is based on issue #140.

**Comment by lanesmith** [comment]
The core functionality sounds good. Here are some comments that I have on the points outlined above:
- I like the idea of having the input to specify between load-zone level or bus level. We could also include functionality to try to infer the granularity if that input is left blank. I'm not sure that we need to specify the number of load zones or the number of buses with demand flexibility. Based on the grid model that is loaded in (mostly the number of load zones and the number of buses) and the naming convention (there is often a noticeable distinction between the names for load zones and buses), we should be able to check that the demand flexibility .csv files that are loaded in make sense.
- Agreed on adding that new parameter to the `DemandFlexibility` struct. It can be set in `read.jl` either by the input or through inference, if required.
- Agree that `_make_bus_demand_flexibility_amount` will need to check whether demand flexibility is provided by load zone or by bus. Using `_make_bus_demand_flexibility_amount` to create the `bus_flex_amt` parameters should be a straightforward update because the load-zone-level functionality is already implemented and the bus-level functionality should mostly take what is provided in the input (since it will already be provided at the bus level). 
- Parameters should be added to the `Sets` struct to identify the buses with demand flexibility (e.g., `flex_load_bus_idx`, `num_flex_load_bus`, and `flex_load_bus_map`). These new values can be computed in the `_make_sets` function in `model.jl`. Then, as suggested above, the demand flexibility decision variables and constraints could be updated to reflect the demand flexibility sets.

Additional questions/comments that come to mind for me are:
- For the time being, should we assume that demand flexibility data provided at the load-zone level is distributed to every load bus? If not, we would have to pass in data about the desired buses with demand flexibility. Eventually, once demand flexibility is integrated to the scenario framework in `PowerSimData`, I imagine that specifying the buses with demand flexibility will produce a demand flexibility .csv that has dimensions of time steps by number of buses with demand flexibility. If this is the case, then we probably don't need to worry about the load-zone-level demand flexibility profiles mapping to anything other than all of the load buses, which it currently does now.
- Should we be concerned about file sizes? I can see some of these file sizes being fairly large, especially for full-year runs that consider the whole U.S. At what point do file sizes become a concern?

**Comment by BainanXia** [comment]
@lanesmith These are great details! 
- Regarding the first bullet: if we would like to infer the "demand flexibility type" parameter solely by dimensionality of inputs,, it could be tricky: an example case, number of buses == number of load zones, etc. Including column names into the identification metric could be safer, i.e. there is no way to have zone_id == bus_id. In this way, we are not limited to define demand flexibility either by zone or by bus, we could do mix, which is of course, fancier but potentially more fragile.
- Regarding the second last bullet: if we plan to have multiple options defined by the user for demand flexibility configuration as proposed by @dongqi-wu , I would prefer if the user chooses "zone", then it is applied to every load bus within the corresponding zone (however, it is not necessarily to have all zones included, this is the similar idea as by "bus"). If we would like to stay with the current implementation, i.e. the zonal approach only, then we need to figure out the work arounds to achieve bus-level configuration using zonal information.
- Regarding the last bullet: It depends. If the file size grows crazy and it takes significant amount of time in file transfer, say more than 30 mins in a good network condition, then we need to find work arounds...
