### ISSUE TITLE
Feature request: Support for Mixed Input Granularity

### ISSUE THREAD

**Issue by dongqi-wu** [Breakthrough-Energy/REISE.jl#157]
# :rocket:

- [ ] Is your feature request essential for your project?

### Describe the workflow you want to enable
In the newest version in #155 the user specified input files `demand_flexibility_up/dn.csv` and `demand_flexibility_cost_up/dn.csv` the user has two options (from a field in demand_flexibility_parameters.csv): `AREA` or `BUS`. The column headers in the input csvs must be corresponding to the parameter. (e.g. if the parameter is `AREA` then the user must give a column of flexibility/cost values for every load zones in the network).

I plan to add support for letting these two types of columns to co-exist. The user can choose to give flexibility/cost data for any number of load zones and any number of load buses in the same csv file. This will allow users to specify some rough numbers for large part of the system and high resolution numbers for a few buses to be studied.

### Describe your proposed implementation
Write additional function and codes in REISE.jl immediately after reading the demand_flexibility struct to convert the input dataframes to the proper format in which all columns correspond to load buses.

e. g.:
Name: preprocess_flexibility
Inputs: demand_flexibility
Description: Go through `demand_flexibility.flex_amt`, `demand_flexibility.cost_up` and `demand_flexibility.cost_dn` which are read from raw input files, and replace them with dataframe that has all bus-level data with shape (hour_num, flexible_bus_num)

Since this approach is more general and can support both type of input files in the current version, the parameter 'input_granularity' will be deleted and the code related to area-level input and distinguishing between `BUS` and `AREA` will be deleted.

### Describe alternatives you've considered, if relevant
Two concerns might be encountered in this implementation

1) When bus IDs and load zone IDs are not unique. For example if there exist a bus called `123` and also a load zone called `123` they cannot be distinguished from the csv header. One way to get around this is to make every ID unique, and another way is to add prefix in the csv headers such as `bus.123` and `area.123`

2) When any load bus get specified two times, one in the area they belong and another with their bus number. For example, if load `123` belong to area `A`, and the input csv has columns for both `123` and `A`. The simplest way is to throw an error, while alternatively the final flexibility amount for bus `123` can be interpreted as the sum of values in column `123` and its part from column `A`. Another way might be re-distributing flexibility values in column `A` to other buses in `A` excluding bus `123`, to make sure the total flexibility in area `A` still sum up to the values in that column.

**Comment by BainanXia** [comment]
@dongqi-wu Sorry for the late reply. Regarding the concerns described above, we kind of talked about those during last meeting a little bit, here is my take:

1. Given we will interpret the raw inputs into buses eventually, I would suggest to keep bus ID as it is and add prefixes to zone IDs, such as `zone.123`. This will also make it easier for further extension in the future, such as `state.123`, `country.123`, etc when dealing with different grid models.
2. I vote for the summation approach as it is consistent with our current `change_table` behavior: the user could scale generator capacities for a `loadzone` and scale by `plant_id` simultaneously, then the resultant behavior is a particular plant is scaled both by zone multiplier and individual multiplier. In this case, we can print out a warning message to let the user know what the program will do based on the inputs.

Feel free to add your inputs as well @danielolsen @rouille @lanesmith @dmuldrew.

**Comment by lanesmith** [comment]
> 1. Given we will interpret the raw inputs into buses eventually, I would suggest to keep bus ID as it is and add prefixes to zone IDs, such as `zone.123`. This will also make it easier for further extension in the future, such as `state.123`, `country.123`, etc when dealing with different grid models.

This sounds fine to me. If we implement it in this way, I will need to change how the headers are defined in in `PreREISE` for the creation of the EFS demand flexibility profiles (I believe the change would need to be made to `map_states.py`). I'm just making this note so I don't forget.

> 2. I vote for the summation approach as it is consistent with our current `change_table` behavior: the user could scale generator capacities for a `loadzone` and scale by `plant_id` simultaneously, then the resultant behavior is a particular plant is scaled both by zone multiplier and individual multiplier. In this case, we can print out a warning message to let the user know what the program will do based on the inputs.

I like the idea about not just throwing an error. I think the summing idea increases the potential for user-created errors. I can see an issue where demand flexibility available is larger than the actual demand at the bus, though the demand flexibility allocated to bus `123` would likely need to be pretty large for this to occur. I like the redistribution idea or even just mapping demand flexibility in zone `A` as it normally would be mapped, then replacing the demand flexibility at bus `123` with the externally specified amount.

EDIT: That being said, any of the inputs pertaining to demand flexibility availability could be larger than the actual demand at the bus (though it seems that it would be easier to do that at the bus level rather rather than the zone level, especially since we provide demand at the zone level, so there is a reference for the magnitude of potential demand flexibility). In addition to checks on the input data (e.g., checking that the demand flexibility up and demand flexibility down profiles all have the same inputs), there might need to be some check following the distribution of the demand and any distribution of the demand flexibility to make sure that available demand flexibility does not exceed available demand.

**Comment by kasparm** [comment]
@BainanXia pointed me to this feature request today.
Regarding 2., I think it would be most natural in case the user sets area and specific bus in area, for the bus specified value to be subtracted from the area value. In this way the user can specify a total for the area and specify individual buses in the area. I would still throw an "error" so the user knows what is happening.
I understand this choice will differ from the current `change_table` behavior. We could mention that in the "error" message.
